language: python
python:
  - "3.6"
install:
  - pip install flake8
script:  
  - flake8 dtat_discord.py cmd/ services/ tests/ --count
  - echo 'PREFIX = "!"
DTAT_HOST_URL = ""
FIRST_ENDING = ""
DEFAULT_ENDING = ""
LAST_ENDING = ""
ERROR = ""' > conf.py
  - python setup.py pytest