language: python
python:
  - "3.6"
install:
  - pip install flake8
script:  
  - flake8 dtat_discord.py commands/ services/ tests/ --count
  - mv conf_example.py conf.py
  - python setup.py pytest