language: python
python:
  - "3.6"
install:
  - pip install flake8
script:  
  - flake8 dtat_discord.py cmd/ services/ tests/ --count
  - echo "DTAT_HOST_URL = ''\nFIRST_ENDING = ''\nDEFAULT_ENDING = ''\nLAST_ENDING = ''\nERROR = ''" > conf.py
  - python setup.py pytest